In [3]:
import numpy as np
import matplotlib.pyplot as plt
from dataclasses import dataclass
from typing import Optional, Tuple
import spectral_density as sd
import correlator as cor

In [18]:
a = cor.make_tau_grid(30)
a

array([0.03333333, 0.06666667, 0.1       , 0.13333333, 0.16666667,
       0.2       , 0.23333333, 0.26666667, 0.3       , 0.33333333,
       0.36666667, 0.4       , 0.43333333, 0.46666667, 0.5       ,
       0.53333333, 0.56666667, 0.6       , 0.63333333, 0.66666667,
       0.7       , 0.73333333, 0.76666667, 0.8       , 0.83333333,
       0.86666667, 0.9       , 0.93333333, 0.96666667])

In [22]:
b = a[: , None]
c = a[None, :]
b

array([[0.03333333],
       [0.06666667],
       [0.1       ],
       [0.13333333],
       [0.16666667],
       [0.2       ],
       [0.23333333],
       [0.26666667],
       [0.3       ],
       [0.33333333],
       [0.36666667],
       [0.4       ],
       [0.43333333],
       [0.46666667],
       [0.5       ],
       [0.53333333],
       [0.56666667],
       [0.6       ],
       [0.63333333],
       [0.66666667],
       [0.7       ],
       [0.73333333],
       [0.76666667],
       [0.8       ],
       [0.83333333],
       [0.86666667],
       [0.9       ],
       [0.93333333],
       [0.96666667]])

In [16]:
w = sd.make_frequency_grid()
w

array([1.00000000e-04, 1.04712855e-04, 1.09647820e-04, 1.14815362e-04,
       1.20226443e-04, 1.25892541e-04, 1.31825674e-04, 1.38038426e-04,
       1.44543977e-04, 1.51356125e-04, 1.58489319e-04, 1.65958691e-04,
       1.73780083e-04, 1.81970086e-04, 1.90546072e-04, 1.99526231e-04,
       2.08929613e-04, 2.18776162e-04, 2.29086765e-04, 2.39883292e-04,
       2.51188643e-04, 2.63026799e-04, 2.75422870e-04, 2.88403150e-04,
       3.01995172e-04, 3.16227766e-04, 3.31131121e-04, 3.46736850e-04,
       3.63078055e-04, 3.80189396e-04, 3.98107171e-04, 4.16869383e-04,
       4.36515832e-04, 4.57088190e-04, 4.78630092e-04, 5.01187234e-04,
       5.24807460e-04, 5.49540874e-04, 5.75439937e-04, 6.02559586e-04,
       6.30957344e-04, 6.60693448e-04, 6.91830971e-04, 7.24435960e-04,
       7.58577575e-04, 7.94328235e-04, 8.31763771e-04, 8.70963590e-04,
       9.12010839e-04, 9.54992586e-04, 1.00000000e-03, 1.04712855e-03,
       1.09647820e-03, 1.14815362e-03, 1.20226443e-03, 1.25892541e-03,
      

In [13]:
def make_frequency_grid(
    wmin=1e-4,
    wsplit=1.0,
    wmax=40.0,
    nlog=200,
    nlin=400
):
    """
    Build a mixed log-linear frequency grid in units of T:
        x = omega / T

    Returns
    -------
    w : np.ndarray
        Frequency grid
    """
    w_log = np.logspace(np.log10(wmin), np.log10(wsplit), nlog, endpoint=False)
    w_try = np.linspace(wmin, wsplit, nlog)
    w_lin = np.linspace(wsplit, wmax, nlin)
    w = np.unique(np.concatenate([w_log, w_lin]))
    return w_log, w_lin, w_try

In [17]:
def smooth_switch(w, Lambda=3.0, sharpness=4.0):
    """
    Smoothly turn on the UV contribution around Lambda.

    f(w) ~ 0 for w << Lambda
    f(w) ~ 1 for w >> Lambda
    """
    x = (w / Lambda) ** sharpness
    return x / (1.0 + x)

smooth_switch(w)

array([1.23456790e-18, 1.48427708e-18, 1.78449354e-18, 2.14543312e-18,
       2.57937794e-18, 3.10109436e-18, 3.72833546e-18, 4.48244512e-18,
       5.38908435e-18, 6.47910445e-18, 7.78959685e-18, 9.36515525e-18,
       1.12593931e-17, 1.35367679e-17, 1.62747746e-17, 1.95665826e-17,
       2.35242064e-17, 2.82823167e-17, 3.40028235e-17, 4.08803854e-17,
       4.91490334e-17, 5.90901349e-17, 7.10419676e-17, 8.54112310e-17,
       1.02686885e-16, 1.23456790e-16, 1.48427708e-16, 1.78449354e-16,
       2.14543312e-16, 2.57937794e-16, 3.10109436e-16, 3.72833546e-16,
       4.48244512e-16, 5.38908435e-16, 6.47910445e-16, 7.78959685e-16,
       9.36515525e-16, 1.12593931e-15, 1.35367679e-15, 1.62747746e-15,
       1.95665826e-15, 2.35242064e-15, 2.82823167e-15, 3.40028235e-15,
       4.08803854e-15, 4.91490334e-15, 5.90901349e-15, 7.10419676e-15,
       8.54112310e-15, 1.02686885e-14, 1.23456790e-14, 1.48427708e-14,
       1.78449354e-14, 2.14543312e-14, 2.57937794e-14, 3.10109436e-14,
      